#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Copyright (c) 2018 Jared Daniel Carbonell Recomendable. All rights reserved.

import os
import getpass
import sys
import subprocess

def get_username():
    '''Return the username of the currently logged in user.'''
    return getpass.getuser()

def list_dir():
    '''Return a sorted list of directories in the current working directory.'''
    return sorted(os.listdir())

def assist_bash(string, symbol):
    '''Assist Bash to recognise the input symbol.'''
    new_string = string.split(symbol)
    string = ''
    if len(new_string) == 1:
        string = new_string[0]
    else:
        for i in range(len(new_string)):
            if i == len(new_string) - 1:
                string += new_string[i]
            else:
                string += new_string[i] + '\\{}'.format(symbol)
    return string

def auto_nav(string, count):
    '''Automagically navigate to the latest folder in Dropbox, without
    assisting Bash.'''
    os.chdir(string)
    while count > 0:
        string += str(list_dir()[-1]) + '/'
        os.chdir(string)
        count -= 1
    return string

def prep_str(flag, nav_flag=-1):
    '''Prepare the string to pass into the bash shell later to open the
    appropriate directory in Nautilus.'''
    # Administrative Activiteis
    string = '/home/{}/Dropbox/'.format(get_username())
    os.chdir(string)

    # Deal with HOME Contents
    if flag == 0:
        string += 'HOME/'
        string = auto_nav(string, 3)

    # Deal with YIJC
    elif flag == 1:
        string += 'YIJC/'

    # Deal with Projects
    elif flag == 3:
        string += 'Projects/'
        string = auto_nav(string, 3)

    # Deal with Media
    elif flag == 4:
        string += 'Media/'

    # Deal with YIJC 2018 Contents
    elif flag == 2:
        string += 'YIJC/2018/'
        subject_directory = {
            0: '0ADMIN/',
            1: '1GP/',
            3: '3MA/',
            4: '4PH/',
            5: '5CP/',
            6: '6EC/',
            7: '7CCA/'
        }
        if nav_flag == 2:
            string += '2PW/'
        else:
            try:
                string += subject_directory[nav_flag]
                string = auto_nav(string, 3)
            except KeyError:
                return 1, 'ERROR'
    else:
        return 1, 'ERROR'

    # Assist Bash in recognising special symbols
    symbol_fix = (' ', "'", '"', '(', '[', '{', '<', ')', ']', '}', '>', '&')
    for symbol in symbol_fix:
        string = assist_bash(string, symbol)

    return 0, string

def run(flag, nav_flag=-1):
    '''Carry out the process of navigating to the latest directory based on
    user's entered arguments. This is the first function called when the program
    is run in the terminal.'''
    result = prep_str(flag, nav_flag)
    if result[0] == 0:
        to_run = 'nautilus {}'.format(result[1])
        subprocess.run(['bash', '-c', to_run])
    else:
        show_help()

def show_help():
    '''Show the help documentation for the program.'''
    help_doc = '''Usage: cdl [options] [directories]

Options:
  -h, --help      show this help message and exit
  -H, --home      go to the latest directory in ~/Dropbox/HOME/
  -M, --media     go to ~/Dropbox/Media/
  -P, --projects  go to the latest directory in ~/Dropbox/Projects/
  -Y, --yijc      go to ~/Dropbox/YIJC/
  -n, --nav       based on the given directories flag, go to the latest respective directory in ~/Dropbox/YIJC/

Directories (can be called when -n flag is passed into the program):
  18admin         go to the latest directory in ~/Dropbox/YIJC/2018/0ADMIN
  18gp            go to the latest directory in ~/Dropbox/YIJC/2018/1GP
  18pw            go to the latest directory in ~/Dropbox/YIJC/2018/2PW
  18ma            go to the latest directory in ~/Dropbox/YIJC/2018/3MA
  18ph            go to the latest directory in ~/Dropbox/YIJC/2018/4PH
  18cp            go to the latest directory in ~/Dropbox/YIJC/2018/5CP
  18ec            go to the latest directory in ~/Dropbox/YIJC/2018/6EC
  18cca           go to the latest directory in ~/Dropbox/YIJC/2018/7CCA'''
    print(help_doc)

if __name__ == '__main__':
    if len(sys.argv) == 2:
        options = {
            '-H'        : 0,
            '--home'    : 0,
            '-Y'        : 1,
            '--yijc'    : 1,
            '-P'        : 3,
            '--projects': 3,
            '-M'        : 4,
            '--media'   : 4
        }
        try:
            run(options[sys.argv[1]])
        except KeyError:
            show_help()
    elif len(sys.argv) == 3:
        if sys.argv[1] in ('-n', '--nav'):
            nav_options = {
                '18admin': 0,
                '18gp'   : 1,
                '18pw'   : 2,
                '18ma'   : 3,
                '18ph'   : 4,
                '18cp'   : 5,
                '18ec'   : 6,
                '18cca'  : 7
            }
            try:
                run(2, nav_options[sys.argv[2]])
            except KeyError:
                show_help()
        else:
            show_help()
    else:
        show_help()
