#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Copyright (c) 2018 Jared Daniel Carbonell Recomendable. All rights reserved.

import sys
import subprocess

def run(flag):
    '''Carry out the process of launching the requested application. This is the
    first function called when the program is run in the terminal.'''
    insertion = {
        0 : 'google-chrome --incognito',
        1 : 'firefox --private-window',
        2 : 'nautilus ~/Apps/',
        3 : 'nautilus ~/Dropbox/',
        4 : 'nautilus ~/.local/bin/',
        5 : 'cd ~ && sudo ./Apps/arduino-1.8.5/arduino',
        6 : 'cd ~ && ./Apps/eagle-9.1.0/eagle',
        7 : 'cd ~ && ./Apps/etcher-electron-1.4.4-x86_64/etcher-electron-1.4.4-x86_64.AppImage',
        8 : 'cd ~ && ./Apps/fritzing-0.9.3b.linux.AMD64/Fritzing',
        9 : 'cd ~ && ./Apps/peazip_portable-6.6.0.LINUX.x86_64.GTK2/peazip',
        10: 'cd ~/Apps/tor-browser_en-US/ && ./start-tor-browser.desktop',
        11: 'cd ~ && ./Apps/coursemology-linux-x64/coursemology',
        12: 'thunderbird',
        13: 'jupyter-notebook --no-browser',
        14: 'cd ~ && ./Apps/freemind-bin-1.0.1/freemind.sh',
        15: 'cd ~ && ./Apps/whats-app-web-linux-x64/whats-app-web',
        16: 'sudo mu-editor',
        17: 'anki'
    }
    try:
        to_run = insertion[flag]
        subprocess.run(['bash', '-c', to_run])
    except KeyError:
        show_help()

def show_help():
    '''Show the help documentation for the program.'''
    help_doc = '''Usage: launch [options]

Options:
  anki          launch Anki
  apps          launch Nautilus with ~/Apps/ open
  arduino       launch Arduino
  chrome        launch Chrome in incognito mode
  coursemology  launch YIJC Coursemology
  dropbox       launch Nautilus with Dropbox root directory open
  eagle         launch Autodesk Eagle
  etcher        launch Etcher
  firefox       launch Firefox in a Private Window
  fritzing      launch Fritzing
  jupyter       launch Jupyter Notebook without launching a browser
  local-bin     launch Nautilus with the directory containing local binaries
  mail          launch Thunderbird
  mindmap       launch FreeMind (mind-mapping software)
  mu            launch Mu Editor
  peazip        launch Peazip
  tor           launch Tor
  whatsapp      launch WhatsApp (desktop program)'''
    print(help_doc)

if __name__ == '__main__':
    if len(sys.argv) == 2:
        options = {
            'chrome'      :  0,
            'firefox'     :  1,
            'apps'        :  2,
            'dropbox'     :  3,
            'local-bin'   :  4,
            'arduino'     :  5,
            'eagle'       :  6,
            'etcher'      :  7,
            'fritzing'    :  8,
            'peazip'      :  9,
            'tor'         : 10,
            'coursemology': 11,
            'mail'        : 12,
            'jupyter'     : 13,
            'mindmap'     : 14,
            'whatsapp'    : 15,
            'mu'          : 16,
            'anki'        : 17
        }
        try:
            run(options[sys.argv[1]])
        except KeyError:
            show_help()
    else:
        show_help()
