#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Copyright (c) 2018-2020 Jared Daniel Carbonell Recomendable.

import os
import getpass
import sys
import subprocess

file_manager = "pcmanfm"
home_dir = "home"

def get_username():
    return getpass.getuser()

def list_dir():
    '''Return a list of directories in the current working directory. Sorted in
    alphabetical order, ascending order.'''
    return sorted(os.listdir())

def recognise_special_symbol(string, symbol):
    '''Include input symbol into the string that has been input from
    the shell.'''
    new_string = string.split(symbol)
    string = ''
    if len(new_string) == 1:
        string = new_string[0]
    else:
        for i in range(len(new_string)):
            if i == len(new_string) - 1:
                string += new_string[i]
            else:
                string += new_string[i] + '\\{}'.format(symbol)
    return string

def auto_nav(string, count):
    '''Automagically navigate to the latest folder in Dropbox'''
    os.chdir(string)
    while count > 0:
        string += str(list_dir()[-1]) + '/'
        os.chdir(string)
        count -= 1
    return string

def prep_str(flag, nav_flag=-1):
    '''Prepare the string to pass into the shell later to open the
    appropriate directory in the file manager.'''
    # Administrative Activities
    string = '/{}/{}/Dropbox/'.format(home_dir, get_username())
    os.chdir(string)

    # Deal with General Contents
    if flag != 2:
        category_directory = {
            0: 'HOME/',
            1: 'UoA/',
            3: 'Projects/',
            4: 'Media/'
        }
        string += category_directory[flag]
        if flag in (0, 3):
            string = auto_nav(string, 3)

    # Deal with UoA Contents
    else:
        string += 'UoA/2020/'
        subject_directory = {
            0: 'ADMIN/',
            1: 'BOOKS/',
            2: 'ENGGEN115/',
            3: 'ENGGEN121/',
            4: 'ENGGEN140/',
            5: 'ENGSCI111/',
            6: 'BOOKS/ENGGEN115/',
            7: 'BOOKS/ENGGEN121/',
            8: 'BOOKS/ENGGEN140/',
            9: 'BOOKS/ENGSCI111/',
        }
        string += subject_directory[nav_flag]
        if nav_flag not in (1, 6, 7, 8, 9):
            string = auto_nav(string, 3)

    # Assist the shell in recognising special symbols
    symbol_fix = (' ', "'", '"', '(', '[', '{', '<', ')', ']', '}', '>', '&')
    for symbol in symbol_fix:
        string = recognise_special_symbol(string, symbol)

    return string

def run(flag, nav_flag=-1):
    '''Carry out the process of navigating to the latest directory based on
    user's entered arguments. This is the first function called when the program
    is run in the terminal.'''
    result = prep_str(flag, nav_flag)
    to_run = '{} {}'.format(file_manager, result)
    subprocess.run(['bash', '-c', to_run])

def show_help():
    '''Show the help documentation for the program.'''
    help_doc = '''Usage: cdl [options] [directories]

Options:
  -h, --help      show this help message and exit
  -H, --home      go to the latest directory in ~/Dropbox/HOME/
  -M, --media     go to ~/Dropbox/Media/
  -P, --projects  go to the latest directory in ~/Dropbox/Projects/
  -U  --uni       go to ~/Dropbox/UoA/

Directories (can be called when -n flag is passed into the program):
  admin  go to the latest directory in ~/Dropbox/UoA/2020/ADMIN/
  books  go to ~/Dropbox/UoA/2020/BOOKS/
  115b   go to ~/Dropbox/UoA/2020/BOOKS/ENGGEN115/
  121b   go to ~/Dropbox/UoA/2020/BOOKS/ENGGEN121/
  140b   go to ~/Dropbox/UoA/2020/BOOKS/ENGGEN140/
  111b   go to ~/Dropbox/UoA/2020/BOOKS/ENGSCI111/
  115    go to the latest directory in ~/Dropbox/UoA/2020/ENGGEN115/
  121    go to the latest directory in ~/Dropbox/UoA/2020/ENGGEN121/
  140    go to the latest directory in ~/Dropbox/UoA/2020/ENGGEN140/
  111    go to the latest directory in ~/Dropbox/UoA/2020/ENGSCI111/'''
    print(help_doc)

if __name__ == '__main__':
    if len(sys.argv) == 2:
        options = {
            '-H'        : 0,
            '--home'    : 0,
            '-U'        : 1,
            '--uni'     : 1,
            '-P'        : 3,
            '--projects': 3,
            '-M'        : 4,
            '--media'   : 4
        }
        try:
            run_flag = options[sys.argv[1]]
            run(run_flag)
        except:
            show_help()
    elif len(sys.argv) == 3:
        if sys.argv[1] in ('-n', '--nav'):
            nav_options = {
                'admin': 0,
                'books': 1,
                '115'  : 2,
                '121'  : 3,
                '140'  : 4,
                '111'  : 5,
                '115b' : 6,
                '121b' : 7,
                '140b' : 8,
                '111b' : 9
            }
            try:
                run_nav_flag = nav_options[sys.argv[2]]
                run(2, run_nav_flag)
            except:
                show_help()
        else:
            show_help()
    else:
        show_help()
